batch_size: 256
epochs: 10
lr: 0.0005

device: cuda:0
num_workers: 4
seed: 1234
use_wandb: False

data_dir: /content/drive/MyDrive/Colabdata/dl_lecture_competition_pub/data

# Evaluation
model_path: 